### ISSUE TITLE
validate on blur

### ISSUE THREAD

**Issue by ccoloma** [koliseoapi/react-data-input#3]
Getting a validation error just after setting an input value may be useful, cause you don't have to wait to submit the form. You can do it yourself using `onBlur` and the `validate` method, but we could add it to `BoundComponent` as a default. 

@icoloma: Does this make sense?

**Comment by icoloma** [comment]
Defaulting to validate on blur is, more frequently than not, super distracting. Particularly empty fields, where you don't know that the field is required until you focus on the next field, then have to focus back. With mouse-based users (the majority) this is a really inefficient way of interacting with the form. 

It may be solved by marking the required fields in the UI, but (a) it's more work for the developer, (b) new source of bugs and (c) also something that the user learns with time interacting with the platform, not the first or second time. I'd go with [Jakob's Law](https://lawsofux.com/jakobs-law) and do what is most common on other websites, which is to wait until form submission to learn what is incorrect.
